const titleBackdrop = new URL('../assets/game/backdrops/title-backdrop.png', import.meta.url).href;
const holyKnight = new URL('../assets/game/units/holy-knight.png', import.meta.url).href;
const wildArcher = new URL('../assets/game/units/wild-archer.png', import.meta.url).href;
const emberMage = new URL('../assets/game/units/ember-mage.png', import.meta.url).href;
const boneWarden = new URL('../assets/game/units/bone-warden.png', import.meta.url).href;
const graveRanger = new URL('../assets/game/units/grave-ranger.png', import.meta.url).href;
const ashPriest = new URL('../assets/game/units/ash-priest.png', import.meta.url).href;
const radiantSlash = new URL('../assets/game/effects/radiant-slash.png', import.meta.url).href;
const skystingArrow = new URL('../assets/game/effects/skysting-arrow.png', import.meta.url).href;
const cinderBurst = new URL('../assets/game/effects/cinder-burst.png', import.meta.url).href;
const graveCleave = new URL('../assets/game/effects/grave-cleave.png', import.meta.url).href;
const blackfeatherShot = new URL('../assets/game/effects/blackfeather-shot.png', import.meta.url).href;
const ashHex = new URL('../assets/game/effects/ash-hex.png', import.meta.url).href;
const chapelChestClosed = new URL('../assets/game/props/chapel-chest-closed.png', import.meta.url).href;
const chapelChestOpen = new URL('../assets/game/props/chapel-chest-open.png', import.meta.url).href;
const terrainGrassA = new URL('../assets/game/terrain/terrain-grass-a.png', import.meta.url).href;
const terrainGrassB = new URL('../assets/game/terrain/terrain-grass-b.png', import.meta.url).href;
const terrainMossA = new URL('../assets/game/terrain/terrain-moss-a.png', import.meta.url).href;
const terrainMossB = new URL('../assets/game/terrain/terrain-moss-b.png', import.meta.url).href;
const terrainStoneA = new URL('../assets/game/terrain/terrain-stone-a.png', import.meta.url).href;
const terrainStoneB = new URL('../assets/game/terrain/terrain-stone-b.png', import.meta.url).href;
const terrainSanctumA = new URL('../assets/game/terrain/terrain-sanctum-a.png', import.meta.url).href;
const obstacleRubbleBarricade = new URL('../assets/game/props/obstacle-rubble-barricade.png', import.meta.url).href;
const lightTorch = new URL('../assets/game/props/light-torch.png', import.meta.url).href;
const sanctumBrazier = new URL('../assets/game/props/sanctum-brazier.png', import.meta.url).href;

export const IMAGE_ASSETS = [
  { key: 'title-backdrop', url: titleBackdrop },
  { key: 'holy-knight', url: holyKnight },
  { key: 'wild-archer', url: wildArcher },
  { key: 'ember-mage', url: emberMage },
  { key: 'bone-warden', url: boneWarden },
  { key: 'grave-ranger', url: graveRanger },
  { key: 'ash-priest', url: ashPriest },
  { key: 'radiant-slash', url: radiantSlash },
  { key: 'skysting-arrow', url: skystingArrow },
  { key: 'cinder-burst', url: cinderBurst },
  { key: 'grave-cleave', url: graveCleave },
  { key: 'blackfeather-shot', url: blackfeatherShot },
  { key: 'ash-hex', url: ashHex },
  { key: 'chapel-chest-closed', url: chapelChestClosed },
  { key: 'chapel-chest-open', url: chapelChestOpen },
  { key: 'terrain-grass-a', url: terrainGrassA },
  { key: 'terrain-grass-b', url: terrainGrassB },
  { key: 'terrain-moss-a', url: terrainMossA },
  { key: 'terrain-moss-b', url: terrainMossB },
  { key: 'terrain-stone-a', url: terrainStoneA },
  { key: 'terrain-stone-b', url: terrainStoneB },
  { key: 'terrain-sanctum-a', url: terrainSanctumA },
  { key: 'obstacle-rubble-barricade', url: obstacleRubbleBarricade },
  { key: 'light-torch', url: lightTorch },
  { key: 'sanctum-brazier', url: sanctumBrazier }
] as const;
