import { UnitBlueprint } from '../core/types';

export const UNIT_BLUEPRINTS: Record<string, UnitBlueprint> = {
  'children-of-the-prophecy-aevum-guardian': {
    id: 'children-of-the-prophecy-aevum-guardian',
    factionId: 'children-of-the-prophecy',
    roleId: 'aevum-guardian',
    name: 'Aevum Guardian',
    className: 'Ascetic Vanguard',
    turnStartCatchPhrase: 'Aevum endures.',
    spriteKey: 'children-of-the-prophecy-aevum-guardian',
    accentColor: 0xd2b37a,
    maxHp: 88,
    move: 4,
    speed: 24,
    attack: 25,
    defense: 14,
    rangeMin: 1,
    rangeMax: 1,
    jump: 1,
    attackName: 'Aevum Staff',
    attackText: 'A disciplined close-quarters strike from the front line.',
    spriteDisplayHeight: 140,
    spriteOffsetX: 0,
    spriteOffsetY: 8,
    idleStyle: 'warden',
    attackStyle: 'blade-arc',
    effectKey: 'the-order-breacher-strike',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Aevum Staff. A disciplined close-quarters strike from the front line.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 1
      }
    ]
  },
  'children-of-the-prophecy-mirage-seer': {
    id: 'children-of-the-prophecy-mirage-seer',
    factionId: 'children-of-the-prophecy',
    roleId: 'mirage-seer',
    name: 'Mirage Seer',
    className: 'Vision Caller',
    turnStartCatchPhrase: 'The veil opens.',
    spriteKey: 'children-of-the-prophecy-mirage-seer',
    accentColor: 0x8db6bf,
    maxHp: 68,
    move: 4,
    speed: 27,
    attack: 24,
    defense: 8,
    rangeMin: 2,
    rangeMax: 3,
    jump: 1,
    attackName: 'Mirage Bind',
    attackText: 'A focused psychic strike from behind the front line.',
    spriteDisplayHeight: 136,
    idleStyle: 'priest',
    attackStyle: 'ash-hex',
    effectKey: 'myrmidons-phase-lash',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Mirage Bind. A focused psychic strike from behind the front line.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 3
      }
    ]
  },
  'children-of-the-prophecy-memory-keeper': {
    id: 'children-of-the-prophecy-memory-keeper',
    factionId: 'children-of-the-prophecy',
    roleId: 'memory-keeper',
    name: 'Memory Keeper',
    className: 'Relic Keeper',
    turnStartCatchPhrase: 'Hold fast to memory.',
    spriteKey: 'children-of-the-prophecy-memory-keeper',
    accentColor: 0xe0c88f,
    maxHp: 64,
    move: 4,
    speed: 26,
    attack: 22,
    defense: 8,
    rangeMin: 2,
    rangeMax: 3,
    jump: 1,
    attackName: 'Relic Pulse',
    attackText: 'A steady support strike that reaches the second line.',
    spriteDisplayHeight: 146,
    spriteOffsetX: 0,
    spriteOffsetY: 4,
    idleStyle: 'mage',
    attackStyle: 'ember-burst',
    effectKey: 'the-order-cautery-charge',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Relic Pulse. A steady support strike that reaches the second line.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 3
      },
      {
        id: 'heal',
        name: 'Memory Mend',
        description: 'Memory Mend. Restore 24 HP to an ally within 3 tiles.',
        kind: 'heal',
        target: 'ally',
        rangeMin: 0,
        rangeMax: 3,
        healAmount: 24,
        effectKey: 'the-order-field-mend'
      }
    ]
  },
  'time-travelers-aion-trooper': {
    id: 'time-travelers-aion-trooper',
    factionId: 'time-travelers',
    roleId: 'aion-trooper',
    name: 'Aion Trooper',
    className: 'Chrono Vanguard',
    turnStartCatchPhrase: 'Anchor locked.',
    spriteKey: 'time-travelers-aion-trooper',
    accentColor: 0x7fbfc1,
    maxHp: 88,
    move: 4,
    speed: 25,
    attack: 25,
    defense: 14,
    rangeMin: 1,
    rangeMax: 3,
    jump: 1,
    attackName: 'Chrono Carbine',
    attackText: 'A steady rifle burst that still threatens at close range.',
    spriteDisplayHeight: 140,
    spriteOffsetX: 5,
    spriteOffsetY: 2,
    idleStyle: 'warden',
    attackStyle: 'arrow-flight',
    effectKey: 'the-order-relay-lance',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Chrono Carbine. A steady rifle burst that can answer near or far threats.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 3
      },
      {
        id: 'throw',
        name: 'Anchor Spike',
        description: 'Anchor Spike. Fire a stabilizer round 2 to 4 tiles away.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 4,
        powerModifier: -5,
        attackStyle: 'arrow-flight',
        effectKey: 'the-order-relay-lance'
      }
    ]
  },
  'time-travelers-scavenger-marksman': {
    id: 'time-travelers-scavenger-marksman',
    factionId: 'time-travelers',
    roleId: 'scavenger-marksman',
    name: 'Scavenger Marksman',
    className: 'Expedition Shooter',
    turnStartCatchPhrase: 'I have the angle.',
    spriteKey: 'time-travelers-scavenger-marksman',
    accentColor: 0xc88b4f,
    maxHp: 70,
    move: 5,
    speed: 29,
    attack: 23,
    defense: 9,
    rangeMin: 2,
    rangeMax: 4,
    jump: 1,
    attackName: 'Scrapline Shot',
    attackText: 'Long-range rifle pressure with good board reach.',
    spriteDisplayHeight: 155,
    spriteOffsetX: 10,
    spriteOffsetY: 15,
    idleStyle: 'ranger',
    attackStyle: 'feather-shot',
    effectKey: 'the-order-tracer-volley',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Scrapline Shot. Long-range rifle pressure from the back line.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 4
      },
      {
        id: 'steal',
        name: 'Salvage Sweep',
        description: 'Salvage Sweep. Slip in close and strip a carried drop before the target falls.',
        kind: 'steal',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 1,
        effectKey: 'the-order-strip-gear'
      }
    ]
  },
  'time-travelers-chronomedic': {
    id: 'time-travelers-chronomedic',
    factionId: 'time-travelers',
    roleId: 'chronomedic',
    name: 'Chronomedic',
    className: 'Field Restorer',
    turnStartCatchPhrase: 'Stay in phase.',
    spriteKey: 'time-travelers-chronomedic',
    accentColor: 0xe0c88f,
    maxHp: 66,
    move: 4,
    speed: 27,
    attack: 22,
    defense: 8,
    rangeMin: 2,
    rangeMax: 3,
    jump: 1,
    attackName: 'Reactor Pulse',
    attackText: 'A compact chrono burst for reliable mid-range damage.',
    spriteDisplayHeight: 146,
    spriteOffsetX: -1,
    spriteOffsetY: 6,
    idleStyle: 'mage',
    attackStyle: 'ember-burst',
    effectKey: 'the-order-cautery-charge',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Reactor Pulse. Reliable mid-range chrono discharge.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 3
      },
      {
        id: 'heal',
        name: 'Rewind Patch',
        description: 'Rewind Patch. Restore 24 HP to an ally within 3 tiles.',
        kind: 'heal',
        target: 'ally',
        rangeMin: 0,
        rangeMax: 3,
        healAmount: 24,
        effectKey: 'the-order-field-mend'
      }
    ]
  },
  'the-order-house-marshal': {
    id: 'the-order-house-marshal',
    factionId: 'the-order',
    roleId: 'house-marshal',
    name: 'House Marshal',
    className: 'Surface Commander',
    turnStartCatchPhrase: 'Hold the line.',
    spriteKey: 'the-order-house-marshal',
    accentColor: 0xc7a35e,
    maxHp: 92,
    move: 4,
    speed: 24,
    attack: 26,
    defense: 16,
    rangeMin: 1,
    rangeMax: 1,
    jump: 1,
    attackName: 'Breacher Strike',
    attackText: 'Heavy close-quarters assault. Strongest on high ground.',
    spriteDisplayHeight: 140,
    idleStyle: 'knight',
    attackStyle: 'blade-arc',
    effectKey: 'the-order-breacher-strike',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Breacher Strike. Heavy close-quarters assault that thrives on high ground.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 1
      },
      {
        id: 'throw',
        name: 'Relay Lance',
        description: 'Relay Lance. Launch a hardened signal spear 2 to 4 tiles away.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 4,
        powerModifier: -6,
        attackStyle: 'arrow-flight',
        effectKey: 'the-order-relay-lance'
      }
    ]
  },
  'the-order-squire-operative': {
    id: 'the-order-squire-operative',
    factionId: 'the-order',
    roleId: 'squire-operative',
    name: 'Squire Operative',
    className: 'Recon Marksman',
    turnStartCatchPhrase: 'Marked and ready.',
    spriteKey: 'the-order-squire-operative',
    accentColor: 0xb55f53,
    maxHp: 72,
    move: 5,
    speed: 28,
    attack: 22,
    defense: 10,
    rangeMin: 2,
    rangeMax: 4,
    jump: 1,
    attackName: 'Tracer Volley',
    attackText: 'Long-range burst. Punishes exposed targets.',
    spriteDisplayHeight: 136,
    idleStyle: 'archer',
    attackStyle: 'arrow-flight',
    effectKey: 'the-order-tracer-volley',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Tracer Volley. Long-range burst for exposed targets.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 4
      },
      {
        id: 'steal',
        name: 'Strip Gear',
        description: 'Strip Gear. Slip in close and strip a carried drop before the target falls.',
        kind: 'steal',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 1,
        effectKey: 'the-order-strip-gear'
      }
    ]
  },
  'the-order-banner-surgeon': {
    id: 'the-order-banner-surgeon',
    factionId: 'the-order',
    roleId: 'banner-surgeon',
    name: 'Banner Surgeon',
    className: 'Field Medic',
    turnStartCatchPhrase: 'Steady. Breathe.',
    spriteKey: 'the-order-banner-surgeon',
    accentColor: 0xde8b5e,
    maxHp: 64,
    move: 4,
    speed: 26,
    attack: 24,
    defense: 8,
    rangeMin: 2,
    rangeMax: 3,
    jump: 1,
    attackName: 'Cautery Charge',
    attackText: 'Mid-range surgical blast with reliable damage.',
    spriteDisplayHeight: 146,
    idleStyle: 'mage',
    attackStyle: 'ember-burst',
    effectKey: 'the-order-cautery-charge',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Cautery Charge. Focused mid-range shot for reliable damage.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 3
      },
      {
        id: 'heal',
        name: 'Field Mend',
        description: 'Field Mend. Restore 24 HP to an ally within 3 tiles.',
        kind: 'heal',
        target: 'ally',
        rangeMin: 0,
        rangeMax: 3,
        healAmount: 24,
        effectKey: 'the-order-field-mend'
      }
    ]
  },
  'myrmidons-tide-legionary': {
    id: 'myrmidons-tide-legionary',
    factionId: 'myrmidons',
    roleId: 'tide-legionary',
    name: 'Tide Legionary',
    className: 'Shock Infantry',
    turnStartCatchPhrase: 'Break the shore.',
    spriteKey: 'myrmidons-tide-legionary',
    accentColor: 0x48a79c,
    maxHp: 84,
    move: 4,
    speed: 23,
    attack: 24,
    defense: 13,
    rangeMin: 1,
    rangeMax: 1,
    jump: 1,
    attackName: 'Breaker Cleave',
    attackText: 'Heavy polearm sweep. Brutal when it closes.',
    spriteDisplayHeight: 136,
    idleStyle: 'warden',
    attackStyle: 'grave-cleave',
    effectKey: 'myrmidons-breaker-cleave',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Breaker Cleave. Brutal polearm sweep at close range.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 1,
        rangeMax: 1
      }
    ],
    dropItemId: 'mending-salve'
  },
  'myrmidons-hunter': {
    id: 'myrmidons-hunter',
    factionId: 'myrmidons',
    roleId: 'hunter',
    name: 'Hunter',
    className: 'Amphibious Marksman',
    turnStartCatchPhrase: 'I scent blood.',
    spriteKey: 'myrmidons-hunter',
    accentColor: 0x7fc9ba,
    maxHp: 70,
    move: 5,
    speed: 27,
    attack: 22,
    defense: 10,
    rangeMin: 2,
    rangeMax: 4,
    jump: 1,
    attackName: 'Brine Shot',
    attackText: 'Ranged pressure that softens exposed targets.',
    spriteDisplayHeight: 146,
    spriteOffsetX: -8,
    spriteOffsetY: 15,
    idleStyle: 'ranger',
    attackStyle: 'feather-shot',
    effectKey: 'myrmidons-brine-shot',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Brine Shot. Ranged pressure on exposed targets.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 4
      }
    ],
    dropItemId: 'quick-tonic'
  },
  'myrmidons-spectre': {
    id: 'myrmidons-spectre',
    factionId: 'myrmidons',
    roleId: 'spectre',
    name: 'Spectre',
    className: 'Bio-Psionic Raider',
    turnStartCatchPhrase: 'The deep sees.',
    spriteKey: 'myrmidons-spectre',
    accentColor: 0x7f9fc8,
    maxHp: 66,
    move: 4,
    speed: 25,
    attack: 25,
    defense: 8,
    rangeMin: 2,
    rangeMax: 3,
    jump: 1,
    attackName: 'Phase Lash',
    attackText: 'Psionic strike that spikes from the second line.',
    spriteDisplayHeight: 150,
    idleStyle: 'priest',
    attackStyle: 'ash-hex',
    effectKey: 'myrmidons-phase-lash',
    abilities: [
      {
        id: 'attack',
        name: 'Attack',
        description: 'Phase Lash. Psionic strike from behind the front line.',
        kind: 'attack',
        target: 'enemy',
        rangeMin: 2,
        rangeMax: 3
      }
    ],
    dropItemId: 'mending-salve'
  }
};

export function getUnitBlueprint(blueprintId: string): UnitBlueprint {
  const blueprint = UNIT_BLUEPRINTS[blueprintId];

  if (!blueprint) {
    throw new Error(`Missing unit blueprint: ${blueprintId}`);
  }

  return blueprint;
}

export function getAllUnitBlueprints(): UnitBlueprint[] {
  return Object.values(UNIT_BLUEPRINTS);
}
